sudo: required
services:
    - docker
scripts: 
    - docker build -t wmaalej/node2 .
    - docker images wmaalej/node2

before_deploy:
    - docker login -u wmaalej -p Doubleinfinity123!

deploy:
    provider: script
    script: docker push wmaalej/node2
    on:
        branch: master